### ISSUE TITLE
Extension is not accurate

### ISSUE THREAD

**Issue by RoyRiv3r** [Nerixyz/ttv-tools#1]
Not working every time, sometimes it keeps looping on ads, sometimes it shows 5 secs of ads then refresh it into the stream, is this normal? 
thanks!

**Comment by Nerixyz** [comment]
> Not working every time, sometimes it keeps looping on ads, sometimes it shows 5 secs of ads then refresh it into the stream, is this normal?

* Looping on ads happens bacause the server hasn't yet processed the spoofed packet.
* The delay of 5 seconds is because the reloading is throttled
* On midrolls, the extension will reload the player multiple times as the next ad-id can't be predicted

**Comment by RoyRiv3r** [comment]
Whats the point of this add-on if you can still see ads on a loop, the description says it skip ads which is doesn't, the correct description should be it cuts off ads.

**Comment by Nerixyz** [comment]
> 
> 
> Whats the point of this add-on if you can still see ads on a loop, the description says it skip ads which is doesn't, the correct description should be it cuts off ads.

If you've used YouTube, then you'd know what ad-skipping is. Of course you can still see the ad (that's why there's the replacement). But you see the ad for .1s or 5.1s but then it's skipped. 

Cutting off ads would imply a modification of the stream.

**Comment by RoyRiv3r** [comment]
> 
> 
> > Whats the point of this add-on if you can still see ads on a loop, the description says it skip ads which is doesn't, the correct description should be it cuts off ads.
> 
> If you've used YouTube, then you'd know what ad-skipping is. Of course you can still see the ad (that's why there's the replacement). But you see the ad for .1s or 5.1s but then it's skipped.
> 
> Cutting off ads would imply a modification of the stream.

My bad then sir, thanks for your work.
